<?php
return [
  [
    'title' => '首页',
    'icon' => '',
    'module' => 'system',
    'url' => 'system/index',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 1,
    'nav' => 1,
    'sort' => 0,
    'childs' => [
      [
        'title' => '快捷菜单',
        'icon' => 'aicon ai-caidan',
        'module' => 'system',
        'url' => 'system/quick',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 1,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
            'childs' => [
              [
                'title' => '设置默认等级',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/member/setdefault',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '重置密码',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/member/resetPwd',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 6,
              ],
            ],
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
          ],
          [
            'title' => '清空缓存',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/clear',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 2,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 3,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 4,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 4,
          ],
          [
            'title' => '个人信息设置',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/info',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 5,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 5,
          ],
          [
            'title' => '后台首页',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '后台首页',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/welcome',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '布局切换',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/iframe',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '钩子插件状态',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/hook/hookPluginsStatus',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '设置主题',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/setTheme',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
        ],
      ],
      [
        'title' => '推广设置',
        'icon' => 'aicon ai-quanping',
        'module' => 'system',
        'url' => 'All',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '推荐轮播图',
            'icon' => 'aicon ai-error',
            'module' => 'system',
            'url' => 'system/All/banner',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/all/banner_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/all/banner_edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '分类轮播图',
            'icon' => 'aicon ai-error',
            'module' => 'system',
            'url' => 'system/All/banner2',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/all/banner2_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/all/banner2_edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '值得轮播图',
            'icon' => 'aicon ai-error',
            'module' => 'system',
            'url' => 'system/All/banner3',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/all/banner3_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/all/banner3_edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '文章热门搜索',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/All/search',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/search_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/search_edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '商品热门搜索',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/All/search2',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/search_add2',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/search_edit2',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '商品说明',
            'icon' => 'aicon ai-cha',
            'module' => 'system',
            'url' => 'system/all/goodsexplain',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '关于我们',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/all/aboutus',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '攻略',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/All/strategy',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '奖品列表',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/All/prize',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/prize_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/prize_edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '抽奖说明',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/All/explain',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '分类设置',
        'icon' => 'aicon ai-icon01',
        'module' => 'system',
        'url' => 'classify',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '发现分类',
            'icon' => 'aicon ai-success',
            'module' => 'system',
            'url' => 'system/All/classify',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/classify_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/update_classify',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '值得分类',
            'icon' => 'aicon ai-success',
            'module' => 'system',
            'url' => 'system/All/shopclassify',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/shopclassify_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/shopclassify_edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '值得',
        'icon' => 'aicon ai-success',
        'module' => 'system',
        'url' => 'goods',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '商品',
            'icon' => 'aicon ai-success',
            'module' => 'system',
            'url' => 'system/All/goods',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/goods_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/goods_edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '种草',
            'icon' => 'aicon ai-tuichu',
            'module' => 'system',
            'url' => 'system/All/grass',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/grass_add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/grass_edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '文章',
        'icon' => 'aicon ai-cha',
        'module' => 'system',
        'url' => 'article',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '文章列表',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/All/articlewen',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '详情',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/articlewen_xq',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '图片',
            'icon' => 'aicon ai-mokuaiguanli',
            'module' => 'system',
            'url' => 'system/All/articleimg',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '详情',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/All/articleimg_xq',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '用户',
        'icon' => 'aicon ai-huiyuanliebiao',
        'module' => 'system',
        'url' => 'user',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '用户列表',
            'icon' => 'aicon ai-xitongrizhi-tiaoshi',
            'module' => 'system',
            'url' => 'system/All/user',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
